#ifndef XMLCONSTANTS_H
#define XMLCONSTANTS_H

#define XML_NOATTRIBUTE "__XML_NOATTRIBUTE__"

#define XML_ATTR_AREA "area"
#define XML_ATTR_BDOT "bDot"
#define XML_ATTR_BUILDOPTION "buildOption"
#define XML_ATTR_CGUESS "cGuess"
#define XML_ATTR_CONSTRAINT "constraint"
#define XML_ATTR_CTOT "cTot"
#define XML_ATTR_DATABASE "thermodynamicDatabase"
#define XML_ATTR_EA "ea"
#define XML_ATTR_ICON "iCon"
#define XML_ATTR_ID "ID"
#define XML_ATTR_IONICCHARGE "ionicCharge"
#define XML_ATTR_IONICRADIUS "ionicRadius"
#define XML_ATTR_ISDERIVSTORED "isDerivStored"
#define XML_ATTR_ISSECDERIVCALC "isSecOrdDerivCalc"
#define XML_ATTR_KIND "kind"
#define XML_ATTR_LIMMOLCONDUCTIVITY "limMolConductivity"
#define XML_ATTR_MAXITERNUM "maxIterNum"
#define XML_ATTR_MAXRELATIVEERROR "maxRelativeError"
#define XML_ATTR_MAXRESIDUAL "maxResidual"
#define XML_ATTR_MIXINGRATIO "mixingRatio"
#define XML_ATTR_MODE "mode"
#define XML_ATTR_MODEL "model"
#define XML_ATTR_MOLARVOLUME "molarVolume"
#define XML_ATTR_MOLWEIGHT "molWeight"
#define XML_ATTR_NAME "name"
#define XML_ATTR_PRIMARYSPECIES "primarySpecies"
#define XML_ATTR_REFSPECIES "refSpecies"
#define XML_ATTR_STD "std"
#define XML_ATTR_STEPSNUM "stepsNum"
#define XML_ATTR_TEMP "temp"
#define XML_ATTR_TYPE "type"
#define XML_ATTR_TYPESOLVER "typeSolver"
#define XML_ATTR_ISLOGVALUE "isLog10Value"
#define XML_ATTR_ISRELERROR "isRelError"
#define XML_ATTR_UNITCONC "unitConc"
#define XML_ATTR_VALUE "value"
#define XML_ATTR_WRITEINFO "writeInfo"
#define XML_ATTR_ZERO "zero"
//#define XML_ATTR_STOICHIOMCOEFF "stoichCoeff"

#define XML_TAG_CONSTRAINT "constraint"
#define XML_TAG_FUNCTION "function"
#define XML_TAG_FIRSTGUESS "firstGuess"
#define XML_TAG_LOGK "logK"
#define XML_TAG_LOCALCHEMICALSYSTEMS "localChemicalSystems"
#define XML_TAG_LOCALCHEMICALSYSTEM "localChemicalSystem"
#define XML_TAG_MINERALZONE "mineralZone"
#define XML_TAG_PHASE "phase"
#define XML_TAG_PHASES "phases"
#define XML_TAG_PHASECONTENT "phaseContent"
#define XML_TAG_REACTION "reaction"
#define XML_TAG_REACTIONRATELAW "reactionRateLaw"
#define XML_TAG_REACTIONS "reactions"
#define XML_TAG_KINETICREACTIONS "kineticReactions"
#define XML_TAG_KINETICREACTION "kineticReaction"
#define XML_TAG_SPECIES "species"
#define XML_TAG_TEMP "temp"
#define XML_TAG_TERM "term"

#define XML_TAG_CHEMCOMP "chemicalComposition"
#define XML_TAG_CHEPROOPLUSPLUS "cheprooPlusPlus"
#define XML_TAG_GLOBALCHEMICALSYSTEM "globalChemicalSystem"
#define XML_TAG_REF "ref"
#define XML_TAG_PROOSTLIST "proostList"

// Proost things..to be removed once the object manager contains only "cheproo" stuff
#define XML_ATTR_GLOBALTIME0 "globaltime0"
#define XML_ATTR_LOCALTIMESPERDAY "localTimesPerDay"
#define XML_TAG_IMPORTLIST "ImportList"
#define XML_TAG_IMPORT "ImportTask"
#define XML_TAG_TIMEDEF "timeDef"
#define XML_ATTR_NUMOFDIM "nrDim"
#define XML_ATTR_BASICTGT "basicTgt"
#define XML_TAG_SPACEDEF "spaceDef"


#endif
